use_default_settings: true

general:
  instance_name: "Epsilon Search"

search:
  formats:
    - html
    - json

server:
  secret_key: "smileyv2protectepsilonpassword"
  limiter: false
  image_proxy: true
engines:
  - name: brave
    disabled: false

  - name: duckduckgo
    disabled: true

  - name: google cse
    disabled: true

  - name: startpage
    disabled: true

  - name: duckduckgo web
    disabled: true

  - name: mwmbl
    disabled: true

  - name: yep
    disabled: true
